SELECT 
    YEAR(YM) 'YEAR',
    ROUND(AVG(PM_VAL1), 2) 'PM10', -- 평균 미세먼지 오염도
    ROUND(AVG(PM_VAL2), 2) 'PM2.5' -- 평균 초미세먼지 오염도
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원' -- 수원 지역
GROUP BY YEAR
ORDER BY YEAR