SELECT c.CAR_ID, c.CAR_TYPE, CAST((c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
ON p.CAR_TYPE = c.CAR_TYPE
WHERE 
    (NOT EXISTS (
    # 2022년 11월 1일 ~ 11월 30일까지 대여 가능 ID
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    WHERE c.CAR_ID = h.CAR_ID
    AND h.END_DATE >= '2022-11-01' 
    AND h.START_DATE <= '2022-11-30'
))
AND (c.CAR_TYPE = '세단' OR c.CAR_TYPE ='SUV')
AND p.DURATION_TYPE LIKE '30일%'
AND (c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) >= 500000
AND (c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) < 2000000
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC