## 중성화 안 된 동물 추출
WITH intact AS (SELECT *
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE 'Intact%')

SELECT ao.ANIMAL_ID, ao.ANIMAL_TYPE, ao.NAME
FROM ANIMAL_OUTS ao
INNER JOIN intact i 
ON ao.ANIMAL_ID = i.ANIMAL_ID
WHERE ao.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
