SELECT 
    COUNT(fi.FISH_TYPE) FISH_COUNT, 
    fn.FISH_NAME
FROM FISH_INFO fi
INNER JOIN 
    FISH_NAME_INFO fn
ON 
    fi.FISH_TYPE = fn.FISH_TYPE
GROUP BY 
    fi.FISH_TYPE, fn.FISH_NAME
ORDER BY 
    FISH_COUNT DESC