-- 분기 설정
WITH qur AS(
    SELECT  
        CASE 
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 3 AND 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 6 AND 9 THEN '3Q'
            ELSE '4Q'
        END 'QUARTER'
    FROM ECOLI_DATA
)

SELECT *, COUNT(QUARTER) ECOLI_COUNT
FROM qur
GROUP BY QUARTER
ORDER BY QUARTER