WITH may AS (SELECT * # 생산일자 2022년 5월 식품
FROM FOOD_ORDER 
WHERE PRODUCE_DATE LIKE '2022-05%') 

SELECT f.PRODUCT_ID, f.PRODUCT_NAME, sum(m.AMOUNT * f.PRICE) AS TOTAL_SALES
FROM may m 
INNER JOIN FOOD_PRODUCT f ON f.PRODUCT_ID = m.PRODUCT_ID
GROUP BY f.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, f.PRODUCT_ID