WITH ju AS (
    SELECT j.SHIPMENT_ID, j.FLAVOR, SUM(j.TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY j
    GROUP BY j.FLAVOR)

SELECT j.FLAVOR
FROM FIRST_HALF f
RIGHT JOIN ju j
ON f.SHIPMENT_ID = j.SHIPMENT_ID
ORDER BY (j.TOTAL_ORDER + f.TOTAL_ORDER) DESC ## 총 주문량 내림차순
LIMIT 3 ## 상위 3개 