-- 날짜와 CS, 예약 조건 만족
WITH mcdp AS(
    SELECT *
    FROM APPOINTMENT
    WHERE APNT_YMD LIKE '2022-04-13%'
    AND MCDP_CD = 'CS'
    AND APNT_CNCL_YN = 'N'
),
pt AS(
    SELECT APNT_NO, PT_NAME, m.PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
    FROM mcdp m
    INNER JOIN PATIENT p
    ON m.PT_NO = p.PT_NO
)

SELECT APNT_NO, PT_NAME, PT_NO, d.MCDP_CD, DR_NAME, APNT_YMD
FROM DOCTOR d
INNER JOIN pt p
ON d.DR_ID = p.MDDR_ID
ORDER BY APNT_YMD