SELECT 
    MEMBER_ID, 
    MEMBER_NAME, 
    GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' ## 여성회원
AND MONTH(DATE_OF_BIRTH) = '3' ## 3월생
AND TLNO IS NOT NULL ## 전화번호 NULL 제외