-- 총주문량이 3,000 초과
-- 주 성분 과일
WITH fruit AS(
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
)

SELECT fh.FLAVOR
FROM FIRST_HALF fh
INNER JOIN fruit f
ON fh.FLAVOR = f.FLAVOR
WHERE TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC