WITH maxlength AS(
    SELECT ID, f.FISH_TYPE, f.LENGTH
    FROM FISH_INFO f
    INNER JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO  
        GROUP BY FISH_TYPE) a
    ON f.FISH_TYPE = a.FISH_TYPE
    AND f.LENGTH = a.LENGTH)
    

SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO f
INNER JOIN maxlength m
ON f.FISH_TYPE = m.FISH_TYPE
ORDER BY ID