SELECT
    ii.INGREDIENT_TYPE,
    SUM(fl.TOTAL_ORDER) AS TOTAL_ORDER
FROM 
    FIRST_HALF fl 
INNER JOIN 
    ICECREAM_INFO ii 
ON 
    fl.FLAVOR = ii.FLAVOR  
GROUP BY
    ii.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER