## 가장 조회수가 높은 게시글
WITH maxview AS (SELECT b.BOARD_ID
FROM USED_GOODS_BOARD b
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD))

SELECT concat('/home/grep/src/',m.BOARD_ID,'/',f.FILE_ID,f.FILE_NAME,f.FILE_EXT) AS FILE_PATH
FROM maxview m
INNER JOIN USED_GOODS_FILE f
ON m.BOARD_ID = f.BOARD_ID
ORDER BY f.FILE_ID DESC