-- NULL은 10으로 변환.
SELECT 
    COUNT(*)FISH_COUNT, 
    MAX(LENGTH) MAX_LENGTH, 
    FISH_TYPE
FROM (SELECT FISH_TYPE, IFNULL(LENGTH, 10) LENGTH
      FROM FISH_INFO) fish
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE